- ensure that fakeroot is installed

diff --git a/trunk/tools/release/mkdebs b/trunk/tools/release/mkdebs
--- a/trunk/tools/release/mkdebs
+++ b/trunk/tools/release/mkdebs
@@ -9,6 +9,11 @@ DATE=`date +%y%m%d`
 CODEDIR=boson-code-$DATE
 DATADIR=boson-data-$DATE
 
+if [ ! -x fakeroot ]; then
+  echo "ERROR: fakeroot not installed!"
+  exit 1
+fi
+
 
 echo "*** Generating the Boson deb files"
 rm -f boson-code*.tar.gz
