- update the script...   it deletes some stuff and moves stuff around, so i don't trust it enough to   use it on my working directory...   now it creates a separate directory (../../mkdebs.dir/) where it copies   tools,code and data to.   there it'll do a cvs-clean and then start to generate the actual packages.
  note that on my system a cvs-clean is pretty handy, but i believe it'll cause
  some trouble. for example it will definitely break music files, as they are
  not in cvs. so i should probably revert this to a distclean soon

diff --git a/tools/release/mkdebs b/tools/release/mkdebs
--- a/tools/release/mkdebs
+++ b/tools/release/mkdebs
@@ -3,28 +3,59 @@
 # this script should get run from tools/ subdirectory in a standard cvs tree
 # (i.e. with code/ data/ and tools/ in one dir)
 
-cd ../../
+# $ROOTDIR is where code/ data/ and tools/ can be found.
+ROOTDIR="../.."
+
+# The packages will be generated in $ROOTDIR/$TMPDIR.
+TMPDIR="mkdebs.dir"
+
+if [ ! -d $ROOTDIR/code ]; then
+  echo "ERROR: $ROOTDIR/code does not exist"
+  exit 1
+fi
+if [ ! -d $ROOTDIR/data ]; then
+  echo "ERROR: $ROOTDIR/data does not exist"
+  exit 1
+fi
+if [ ! -d $ROOTDIR/tools ]; then
+  echo "ERROR: $ROOTDIR/tools does not exist"
+  exit 1
+fi
+
+cd $ROOTDIR || exit 1
+ROOTDIR=$PWD # this way we support both, absolute and relative dirs in $ROOTDIR
+mkdir -p $TMPDIR || { echo "unable to create $TMPDIR in $ROOTDIR - check permissions!" ; exit 1; }
+cd $TMPDIR || exit 1
+TMPDIR=$PWD # now this one is absolute, too.
 
 DATE=`date +%y%m%d`
 CODEDIR=boson-code-$DATE
 DATADIR=boson-data-$DATE
+
+rm -rf $TMPDIR/$CODEDIR
+rm -rf $TMPDIR/$DATADIR
 
 if [ ! `which fakeroot` ]; then
   echo "ERROR: fakeroot not installed!"
   exit 1
 fi
 
+
 echo "*** Generating the Boson deb files"
-rm -f boson-code*.tar.gz
-rm -f boson-data*.tar.gz
+rm -f $TMPDIR/boson-code*.tar.gz
+rm -f $TMPDIR/boson-data*.tar.gz
 
 echo "**** Preparing code:"
-cd code || exit 1
+#cd $ROOTDIR/code || exit 1
+echo -n "***** Copying..."
+cp -a $ROOTDIR/code $TMPDIR/$CODEDIR
+rm -rf $TMPDIR/$CODEDIR/admin
+cp -a $ROOTDIR/tools/admin $TMPDIR/$CODEDIR/admin || { echo "admin dir could not be copied from tools"; exit 1; }
+echo "done."
 echo -n "***** Cleaning up..."
-#rm -rf debian
-if [ -f Makefile ]; then
-  make distclean
-fi
+cd $TMPDIR/$CODEDIR || exit 1
+make -f admin/Makefile.common cvs-clean > /dev/null 2>&1 || exit 1
+cp -a $ROOTDIR/tools/admin $TMPDIR/$CODEDIR/admin
 echo "done."
 echo "***** Generating Makefiles:"
 make -s -f Makefile.cvs || exit 1
@@ -33,40 +64,26 @@ echo "***** Running ./configure:"
 
 
 echo "**** Preparing data"
-cd ../data/ || exit 1
+#cd $ROOTDIR/data || exit 1
+echo -n "***** Copying..."
+cp -a $ROOTDIR/data $TMPDIR/$DATADIR
+rm -rf $TMPDIR/$DATADIR/admin
+cp -a $ROOTDIR/tools/admin $TMPDIR/$DATADIR/admin || { echo "admin dir could not be copied from tools"; exit 1; }
+echo "done."
 echo -n "***** Cleaning up..."
 #rm -rf debian
-if [ -f Makefile ]; then
-  make distclean
-fi
+cd $TMPDIR/$DATADIR || exit 1
+make -f admin/Makefile.common cvs-clean > /dev/null 2>&1 || exit 1
+cp -a $ROOTDIR/tools/admin $TMPDIR/$DATADIR/admin
 echo "done."
 echo "***** Generating Makefiles..."
 make -s -f Makefile.cvs || exit 1
 echo "***** Running ./configure:"
 ./configure || exit 1
-cd ..
 
-echo "**** Packing code..."
-echo -n "***** Generating tar file..."
-tar c code > $CODEDIR.tar || echo -e "failed.\n**** WARNING: Could not create tar-file for code"
-echo "done."
-
-echo -n "***** Generating gzip file..."
-gzip $CODEDIR.tar || echo -e "failed.\n**** WARNING: Could not create gzip-file for code"
-echo "done."
-
-echo "**** Packing data..."
-echo -n "***** Generating tar file..."
-tar c data > $DATADIR.tar || echo -e "failed.\n**** WARNING: Could not create tar-file for data"
-echo "done."
-
-echo -n "***** Generating gzip file..." 
-gzip $DATADIR.tar || echo -e "failed.\n**** WARNING: Could not create gzip-file for data"
-echo "done."
-
-echo "**** Renaming the dirs"
-mv code $CODEDIR || echo "**** WARNING: Cannot rename the code dir"
-mv data $DATADIR || echo "**** WARNING: Cannot rename the data dir"
+# at this point we have $CODEDIR and $DATADIR in $TMPDIR, both completely
+# (cvs-)cleaned, and ./configure'd.
+# we can start the real stuff now.
 
 #echo "**** Generating debian dirs"
 #echo "***** For code:"
@@ -80,18 +97,15 @@ mv data $DATADIR || echo "**** WARNING: Cannot rename the data dir"
 #cd ..
 
 echo "**** Building the code dir"
-cd $CODEDIR
+cd $TMPDIR/$CODEDIR
 dpkg-buildpackage -rfakeroot
 cd ..
 echo "**** Done."
 echo "Building the data dir"
-cd $DATADIR
+cd $TMPDIR/$DATADIR
 dpkg-buildpackage -rfakeroot
 cd ..
 echo "**** Done"
 
-echo "**** Restoring orginal source dir names"
-mv $CODEDIR code || echo "**** WARNING: Cannot rename the code dir"
-mv $DATADIR data || echo "**** WARNING: Cannot rename the data dir"
-
 echo "*** Finished."
+
